/* Generated By:JavaCC: Do not edit this line. ExpressionParserImpConstants.java */
package com.squid.core.expression.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserImpConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int EXPONENTIATE = 12;
  /** RegularExpression Id. */
  int MULTIPLY = 13;
  /** RegularExpression Id. */
  int DIVIDE = 14;
  /** RegularExpression Id. */
  int LESSTHAN = 15;
  /** RegularExpression Id. */
  int LESSOREQUALTHAN = 16;
  /** RegularExpression Id. */
  int GREATERTHAN = 17;
  /** RegularExpression Id. */
  int GREATEROREQUALTHAN = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int EQUAL = 21;
  /** RegularExpression Id. */
  int NOTEQUAL = 22;
  /** RegularExpression Id. */
  int AROBASE = 23;
  /** RegularExpression Id. */
  int AMPERSAND = 24;
  /** RegularExpression Id. */
  int SHARP = 25;
  /** RegularExpression Id. */
  int MODULO = 26;
  /** RegularExpression Id. */
  int DOLLAR = 27;
  /** RegularExpression Id. */
  int AS = 28;
  /** RegularExpression Id. */
  int FILTER = 29;
  /** RegularExpression Id. */
  int FACET = 30;
  /** RegularExpression Id. */
  int METRIC = 31;
  /** RegularExpression Id. */
  int NULL = 32;
  /** RegularExpression Id. */
  int TRUE = 33;
  /** RegularExpression Id. */
  int FALSE = 34;
  /** RegularExpression Id. */
  int DIGIT = 35;
  /** RegularExpression Id. */
  int LETTER = 36;
  /** RegularExpression Id. */
  int INTEGER = 37;
  /** RegularExpression Id. */
  int STRING_LITERAL = 38;
  /** RegularExpression Id. */
  int STRING_IDENTIFIER = 39;
  /** RegularExpression Id. */
  int IDENTIFIER = 40;
  /** RegularExpression Id. */
  int SPECIAL_IDENTIFIER = 41;
  /** RegularExpression Id. */
  int LPAREN = 42;
  /** RegularExpression Id. */
  int RPAREN = 43;
  /** RegularExpression Id. */
  int LBRACE = 44;
  /** RegularExpression Id. */
  int RBRACE = 45;
  /** RegularExpression Id. */
  int LBRACKET = 46;
  /** RegularExpression Id. */
  int RBRACKET = 47;
  /** RegularExpression Id. */
  int SEMICOLON = 48;
  /** RegularExpression Id. */
  int COMMA = 49;
  /** RegularExpression Id. */
  int DOT = 50;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"*/\"",
    "<token of kind 9>",
    "\"+\"",
    "\"-\"",
    "\"**\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "<OR>",
    "<AND>",
    "\"=\"",
    "\"!=\"",
    "\"@\"",
    "\"&\"",
    "\"#\"",
    "\"%\"",
    "\"$\"",
    "<AS>",
    "<FILTER>",
    "<FACET>",
    "<METRIC>",
    "\"NULL\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "<DIGIT>",
    "<LETTER>",
    "<INTEGER>",
    "<STRING_LITERAL>",
    "<STRING_IDENTIFIER>",
    "<IDENTIFIER>",
    "<SPECIAL_IDENTIFIER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"DATE(\"",
    "\":\"",
  };

}
